[package]
name = "kitty-session-manager"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ksm"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
colored = "3.0.0"
